### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by dafnevk** [EyeofBeholder-NLeSC/python-knime-extension#2]
It would be good to add unit tests for the functions in the knime extension script.

For CSVW Validator,
  - [x] test if, for a valid case, the output is a table of URLs pointing to the corresponding CSV files;
  - [x] test if the validator really fails an invalid case.
 
For CSVW Reader,
  - [x] test if the reader node correctly does column renaming and data type conversion;
  - [x] test if the node fails different invalid inputs.

Also, 
  - [x] test if the validate_metadata_url method fails different inputs.

**Comment by jiqicn** [comment]
Tests to add:
- CSVValidator
  - [ ] failed validation cases
  - [ ] no metadata entrance
- CSVNormalizer
  - [ ] More than one row in the input
  - [ ] Input URL is not valid or not linked to a CSV file
  - [ ] Input CSV file not found in the metadata file

**Comment by jiqicn** [comment]
Check https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaises for testing if a function raises an exception with a set of args.
